# Generated by Django 6.0.2 on 2026-03-14 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_subject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_details', to='quiz_app.result')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.answer')),
            ],
            options={
                'db_table': 'ResultDetails',
            },
        ),
    ]
