# Generated by Django 6.0.2 on 2026-03-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_customuser_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='plain_password',
        ),
    ]
