# Generated by Django 6.0.2 on 2026-03-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_remove_customuser_plain_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='CustomUsers',
        ),
    ]
